version: "3.9"

services:
  elastic:
    image: elasticsearch:8.11.1
    environment:
      xpack.security.transport.ssl.enabled: false
      discovery.type: single-node
      ELASTIC_PASSWORD: MagicWord
    deploy:
      resources:
        limits:
          memory: 3GB
    restart: always
    ports:
      - 9200:9200
  service:
    image: nazarmedykh/es-demo:v1
    depends_on:
      - elastic
    environment:
      AUTH_USER: admin
      AUTH_PASSWORD: dummy-admin-password
      ELASIC_PASSWORD: MagicWord
      ELASTIC_URL: http://18.184.219.110:9200
#      ELASTIC_URL: http://elastic:9200
    restart: always
    ports:
      - 8080:8080

