spring:
  security:
    user:
      name: ${AUTH_USER}
      password: ${AUTH_PASSWORD}
  elasticsearch:
    uris: ${ELASTIC_URL}
    password: ${ELASIC_PASSWORD}
    username: elastic

logging:
  pattern:
    console: '%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable'
  level:
    root: info
    org.zalando.logbook: trace

springdoc:
  api-docs:
    path: /api-docs
